import React, { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../utils/api';
import { Mawb, MawbForm } from '../types';
import { useAuth } from '../hooks/useAuth';
import toast from 'react-hot-toast';
import { fmtDateTime } from '../utils/dateUtils';
import Pagination from '../components/Pagination';
import { isSignerRunning, signCgmContent, downloadSignedCgm, SIGNER_SETUP_MSG } from '../utils/localSigner';

type ModalMode = 'add' | 'edit' | 'part' | 'amend' | 'delete-confirm' | null;

const emptyForm: MawbForm = {
  mawb_no: '', mawb_date: '', origin: '', destination: '',
  total_packages: '', gross_weight: '', customs_house_code: '', profile_id: '',
  flight_no: '', flight_origin_date: '', igm_no: '', igm_date: '',
};

interface InlineHawbRow {
  hawb_no: string;
  origin: string;
  destination: string;
  total_packages: string;
  gross_weight: string;
  item_description: string;
}

const createInlineHawbRow = (origin = '', destination = ''): InlineHawbRow => ({
  hawb_no: '',
  origin,
  destination,
  total_packages: '',
  gross_weight: '',
  item_description: '',
});

const MawbPage: React.FC = () => {
  const { selectedLocation, user } = useAuth();
  const [mawbs, setMawbs] = useState<Mawb[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [modalMode, setModalMode] = useState<ModalMode>(null);
  const [activeMawb, setActiveMawb] = useState<Mawb | null>(null);
  const [form, setForm] = useState<MawbForm>(emptyForm);
  const [saving, setSaving] = useState(false);
  const [signingId, setSigningId] = useState<string | null>(null);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(25);
  const [showTransmitted, setShowTransmitted] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  // Weight/package validation warning
  const [validationWarn, setValidationWarn] = useState('');
  const [inlineHawbs, setInlineHawbs] = useState<InlineHawbRow[]>([]);
  const navigate = useNavigate();

  const fetchMawbs = useCallback(async (p = page, ps = pageSize, transmitted = showTransmitted) => {
    setLoading(true);
    try {
      const res = await api.get('/mawbs', { params: {
        page: p,
        pageSize: ps,
        ...(search ? { search } : {}),
        ...(selectedLocation?.customs_house_code ? { customs_house_code: selectedLocation.customs_house_code } : {}),
      } });
      setMawbs(res.data.data);
      setTotal(res.data.total);
    } catch { toast.error('Failed to load MAWBs'); }
    finally { setLoading(false); }
  }, [search, page, pageSize, selectedLocation?.customs_house_code, showTransmitted]);

  useEffect(() => { fetchMawbs(); }, [fetchMawbs]);

  // Keep destination in sync whenever selectedLocation changes (add mode only)
  useEffect(() => {
    if (modalMode === 'add' && selectedLocation?.iata_code) {
      const dest = selectedLocation.iata_code;
      setForm(prev => ({ ...prev, destination: dest, customs_house_code: deriveChc(dest) }));
    }
  }, [selectedLocation, modalMode]); // eslint-disable-line

  const openAdd = () => {
    setActiveMawb(null);
    setValidationWarn('');
    setInlineHawbs([]);
    const dest = selectedLocation?.iata_code || '';
    setForm({
      ...emptyForm,
      destination: dest,
      customs_house_code: deriveChc(dest) || selectedLocation?.customs_house_code || user?.customs_house_code || '',
      profile_id: user?.profile_id || '',
    });
    setModalMode('add');
  };

  const openEdit = (m: Mawb) => {
    setActiveMawb(m);
    setValidationWarn('');
    setInlineHawbs([]);
    setForm({
      mawb_no: m.mawb_no, mawb_date: m.mawb_date?.slice(0, 10) || '',
      origin: m.origin, destination: m.destination,
      total_packages: m.total_packages, gross_weight: m.gross_weight,
      customs_house_code: m.customs_house_code || '',
      profile_id: m.profile_id || '',
      flight_no: m.flight_no || '', flight_origin_date: m.flight_origin_date?.slice(0, 10) || '',
      igm_no: m.igm_no || '', igm_date: m.igm_date?.slice(0, 10) || '',
    });
    setModalMode('edit');
  };

  const openPart = (m: Mawb) => {
    setActiveMawb(m);
    setValidationWarn('');
    setInlineHawbs([]);
    setForm({
      mawb_no: m.mawb_no, mawb_date: m.mawb_date?.slice(0, 10) || '',
      origin: m.origin, destination: m.destination,
      total_packages: m.total_packages, gross_weight: m.gross_weight,
      customs_house_code: m.customs_house_code || '', profile_id: m.profile_id || '',
      flight_no: m.flight_no || '', flight_origin_date: m.flight_origin_date?.slice(0, 10) || '',
      igm_no: m.igm_no || '', igm_date: m.igm_date?.slice(0, 10) || '',
    });
    setModalMode('part');
  };

  const generateHawbRows = (count: number) => {
    if (!count || count <= 0) return;

    const rows: InlineHawbRow[] = [];
    for (let i = 0; i < count; i++) {
      rows.push(createInlineHawbRow(form.origin, form.destination));
    }

    setInlineHawbs(rows);
    setAutoGenerated(true);
  };

  const openAmend = (m: Mawb) => {
    setActiveMawb(m);
    setValidationWarn('');
    setInlineHawbs([]);
    setForm({
      mawb_no: m.mawb_no, mawb_date: m.mawb_date?.slice(0, 10) || '',
      origin: m.origin, destination: m.destination,
      total_packages: m.total_packages, gross_weight: m.gross_weight,
      customs_house_code: m.customs_house_code || '', profile_id: m.profile_id || '',
      flight_no: m.flight_no || '', flight_origin_date: m.flight_origin_date?.slice(0, 10) || '',
      igm_no: m.igm_no || '', igm_date: m.igm_date?.slice(0, 10) || '',
    });
    setModalMode('amend');
  };

  const openDeleteConfirm = (m: Mawb) => {
    setActiveMawb(m);
    setValidationWarn('');
    setInlineHawbs([]);
    setForm({
      mawb_no: m.mawb_no, mawb_date: m.mawb_date?.slice(0, 10) || '',
      origin: m.origin, destination: m.destination,
      total_packages: m.total_packages, gross_weight: m.gross_weight,
      customs_house_code: m.customs_house_code || '', profile_id: m.profile_id || '',
      flight_no: m.flight_no || '', flight_origin_date: m.flight_origin_date?.slice(0, 10) || '',
      igm_no: m.igm_no || '', igm_date: m.igm_date?.slice(0, 10) || '',
    });
    setModalMode('delete-confirm');
  };

  // Validate HAWB totals vs MAWB when weight/packages change
  const checkHawbValidation = async (mawbId: string | undefined, mawbPkgs: string | number, mawbWt: string | number) => {
    if (!mawbId) return;
    try {
      const res = await api.get('/hawbs', { params: { mawb_id: mawbId, pageSize: 1000 } });
      const hawbs = res.data.data || [];
      if (hawbs.length === 0) { setValidationWarn(''); return; }
      const totalPkg = hawbs.reduce((s: number, h: any) => s + Number(h.total_packages), 0);
      const totalWt = hawbs.reduce((s: number, h: any) => s + parseFloat(h.gross_weight), 0);
      const warnings: string[] = [];
      if (Number(mawbPkgs) !== totalPkg) warnings.push(`MAWB packages (${mawbPkgs}) ≠ HAWB total packages (${totalPkg})`);
      if (Math.abs(parseFloat(String(mawbWt)) - totalWt) > 0.01) warnings.push(`MAWB weight (${mawbWt}) ≠ HAWB total weight (${totalWt.toFixed(2)})`);
      setValidationWarn(warnings.join(' | '));
    } catch { /* ignore */ }
  };

  const closeModal = () => {
    setModalMode(null);
    setInlineHawbs([]);
  };

  const addInlineHawbRow = () => {
    setInlineHawbs(prev => [
      ...prev,
      createInlineHawbRow(form.origin, form.destination)
    ]);
    setAutoGenerated(false); // user switched to manual mode
  };

  const updateInlineHawbRow = (index: number, field: keyof InlineHawbRow, value: string) => {
    setInlineHawbs(prev => prev.map((row, rowIndex) => (
      rowIndex === index ? { ...row, [field]: value } : row
    )));
  };

  const removeInlineHawbRow = (index: number) => {
    setInlineHawbs(prev => prev.filter((_, rowIndex) => rowIndex !== index));
  };

  const normalizeInlineHawb = (row: InlineHawbRow): InlineHawbRow => ({
    hawb_no: row.hawb_no.trim(),
    origin: row.origin.trim().toUpperCase(),
    destination: row.destination.trim().toUpperCase(),
    total_packages: row.total_packages.trim(),
    gross_weight: row.gross_weight.trim(),
    item_description: row.item_description.trim(),
  });

  const inlineHawbHasData = (row: InlineHawbRow) => (
    Boolean(row.hawb_no || row.total_packages || row.gross_weight || row.item_description)
  );

  const preparedInlineHawbs = inlineHawbs
    .map(normalizeInlineHawb)
    .filter(inlineHawbHasData);

  const inlineHawbCount = preparedInlineHawbs.length;
  const inlineHawbTotalPackages = preparedInlineHawbs.reduce((sum, row) => sum + (parseInt(row.total_packages, 10) || 0), 0);
  const inlineHawbTotalWeight = preparedInlineHawbs.reduce((sum, row) => sum + (parseFloat(row.gross_weight) || 0), 0);
  const showInlineTotalsWarning = inlineHawbCount > 0 && (
    (String(form.total_packages).trim() !== '' && Number(form.total_packages) !== inlineHawbTotalPackages) ||
    (String(form.gross_weight).trim() !== '' && Math.abs(Number(form.gross_weight) - inlineHawbTotalWeight) > 0.01)
  );

  const handleSave = async () => {
    if (!form.mawb_no || !form.origin || !form.destination) {
      toast.error('MAWB No, Origin and Destination are required'); return;
    }
    if (modalMode === 'add' && form.mawb_no.length !== 11) {
      toast.error('MAWB number must be exactly 11 digits'); return;
    }
    if (modalMode === 'add' && preparedInlineHawbs.length > 0) {
      const seen = new Set<string>();
      for (let index = 0; index < preparedInlineHawbs.length; index += 1) {
        const row = preparedInlineHawbs[index];
        if (!row.hawb_no || !row.origin || !row.destination) {
          toast.error(`Inline HAWB row ${index + 1} needs HAWB No, Origin and Destination`);
          return;
        }
        const hawbKey = row.hawb_no.toUpperCase();
        if (seen.has(hawbKey)) {
          toast.error(`Duplicate HAWB No found in inline rows: ${row.hawb_no}`);
          return;
        }
        seen.add(hawbKey);
      }
    }
    setSaving(true);
    try {
      if (modalMode === 'add') {
        if (preparedInlineHawbs.length > 0) {
          const res = await api.post('/mawbs/with-hawbs', { ...form, hawbs: preparedInlineHawbs });
          const createdHawbs = res.data?.hawbs?.length ?? preparedInlineHawbs.length;
          toast.success(`MAWB created with ${createdHawbs} HAWB${createdHawbs === 1 ? '' : 's'}`);
        } else {
          await api.post('/mawbs', form);
          toast.success('MAWB created');
        }
      } else if (modalMode === 'edit' && activeMawb) {
        await api.put(`/mawbs/${activeMawb.id}`, form);
        toast.success('MAWB updated');
      } else if (modalMode === 'part' && activeMawb) {
        const res = await api.post(`/mawbs/part/${activeMawb.id}`, form);
        toast.success(`Part MAWB created: ${res.data.mawb_no}`);
      } else if (modalMode === 'amend' && activeMawb) {
        const res = await api.post(`/mawbs/amend/${activeMawb.id}`, form);
        toast.success(`Amended MAWB created: ${res.data.mawb_no}`);
      }
      closeModal();
      fetchMawbs();
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Save failed');
    } finally { setSaving(false); }
  };

  const handlePermanentDelete = async () => {
    if (!activeMawb) return;
    setSaving(true);
    try {
      await api.delete(`/mawbs/${activeMawb.id}`);
      toast.success('MAWB permanently deleted');
      setModalMode(null);
      fetchMawbs();
    } catch { toast.error('Delete failed'); }
    finally { setSaving(false); }
  };

  const handleDeleteCopy = async () => {
    if (!activeMawb) return;
    setSaving(true);
    try {
      const res = await api.post(`/mawbs/delete-copy/${activeMawb.id}`, form);
      toast.success(`Delete copy created: ${res.data.mawb_no}`);
      setModalMode(null);
      fetchMawbs();
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Failed');
    } finally { setSaving(false); }
  };

  const handleDownload = async (m: Mawb) => {
    const hawbRes = await api.get('/hawbs', { params: { mawb_id: m.id, pageSize: 1000 } });
    const hawbs = hawbRes.data.data || [];
    if (hawbs.length > 0) {
      const totalPkg = hawbs.reduce((s: number, h: any) => s + Number(h.total_packages), 0);
      const totalWt = hawbs.reduce((s: number, h: any) => s + parseFloat(h.gross_weight), 0);
      const errors: string[] = [];
      if (Number(m.total_packages) !== totalPkg) errors.push(`Packages mismatch: MAWB has ${m.total_packages} but HAWBs total ${totalPkg}`);
      if (Math.abs(parseFloat(String(m.gross_weight)) - totalWt) > 0.01) errors.push(`Weight mismatch: MAWB has ${parseFloat(String(m.gross_weight)).toFixed(2)} KGS but HAWBs total ${totalWt.toFixed(2)} KGS`);
      if (errors.length > 0) {
        toast.error(errors.join('\n'), { duration: 5000 });
        return;
      }
    }
    try {
      const res = await api.post(`/transmissions/generate-cgm/${m.id}`, {});
      const { fileName, fileContent } = res.data;
      const url = window.URL.createObjectURL(new Blob([fileContent], { type: 'text/plain' }));
      const link = document.createElement('a');
      link.href = url;
      link.download = fileName;
      link.click();
      window.URL.revokeObjectURL(url);
      toast.success(`Downloaded: ${fileName}`);
      setShowTransmitted(true);
      fetchMawbs(page, pageSize, true);
    } catch (err: any) {
      toast.error(err.response?.data?.message || 'Download failed');
    }
  };


  const handleDownloadSigned = async (m: Mawb) => {
    const hawbRes = await api.get('/hawbs', { params: { mawb_id: m.id, pageSize: 1000 } });
    const hawbs = hawbRes.data.data || [];
    if (hawbs.length > 0) {
      const totalPkg = hawbs.reduce((s: number, h: any) => s + Number(h.total_packages), 0);
      const totalWt = hawbs.reduce((s: number, h: any) => s + parseFloat(h.gross_weight), 0);
      const errors: string[] = [];
      if (Number(m.total_packages) !== totalPkg) errors.push(`Packages mismatch: MAWB has ${m.total_packages} but HAWBs total ${totalPkg}`);
      if (Math.abs(parseFloat(String(m.gross_weight)) - totalWt) > 0.01) errors.push(`Weight mismatch: MAWB has ${parseFloat(String(m.gross_weight)).toFixed(2)} KGS but HAWBs total ${totalWt.toFixed(2)} KGS`);
      if (errors.length > 0) { toast.error(errors.join('\n'), { duration: 5000 }); return; }
    }
    const running = await isSignerRunning();
    if (!running) { toast.error(SIGNER_SETUP_MSG, { duration: 8000 }); return; }
    setSigningId(m.id);
    try {
      // Reuse the already-generated file so the control number does not increment again
      let fileName: string;
      let fileContent: string;
      try {
        const existing = await api.get(`/transmissions/latest/${m.id}`);
        fileName = existing.data.fileName;
        fileContent = existing.data.fileContent;
      } catch {
        // Not generated yet — generate now (increments control number once)
        const fresh = await api.post(`/transmissions/generate-cgm/${m.id}`, {});
        fileName = fresh.data.fileName;
        fileContent = fresh.data.fileContent;
      }
      toast.loading('Waiting for USB token PIN...', { id: 'sign-toast' });
      const { signature, cert } = await signCgmContent(fileContent);
      toast.dismiss('sign-toast');
      downloadSignedCgm(fileContent, signature, cert, fileName);
      toast.success(`Signed file downloaded: ${fileName.replace(/\.cgm$/i, 'Signed.cgm')}`);
      setShowTransmitted(true);
      fetchMawbs(page, pageSize, true);
    } catch (err: any) {
      toast.dismiss('sign-toast');
      toast.error(err.message || err.response?.data?.message || 'Signing failed');
    } finally {
      setSigningId(null);
    }
  };

  // Auto-derive Customs House Code from destination: IN{DEST}4 e.g. DEL → INDEL4
  const deriveChc = (dest: string) =>
    dest.length >= 3 ? `IN${dest.substring(0, 3).toUpperCase()}4` : '';

  const f = (k: keyof MawbForm, v: string) => {
    setForm(p => {
      const updated = { ...p, [k]: v };
      // Auto-fill customs_house_code when destination changes
      if (k === 'destination') {
        updated.customs_house_code = deriveChc(v);
      }
      return updated;
    });
  };

  const isFreshMawb = (mawbNo: string) => !/-[APD]\d/.test(mawbNo);

  const msgTypeBadge = (t?: string) => {
    const map: Record<string, string> = { F: 'badge-info', A: 'badge-warning', D: 'badge-danger' };
    const labels: Record<string, string> = { F: 'Fresh', A: 'Amend', D: 'Delete' };
    return <span className={`badge ${map[t || 'F'] || 'badge-gray'}`}>{labels[t || 'F'] || t}</span>;
  };

  const statusBadge = (s: string) => {
    const map: Record<string, string> = { draft: 'badge-gray', transmitted: 'badge-info', acknowledged: 'badge-success', error: 'badge-danger' };
    return <span className={`badge ${map[s] || 'badge-gray'}`}>{s}</span>;
  };

  // Flight details shown in edit/part/amend only (delete-confirm has its own layout)
  const showFlightDetails = modalMode === 'edit' || modalMode === 'part' || modalMode === 'amend';
  const mawbNoDisabled = modalMode === 'edit';

  const modalTitle: Record<string, string> = {
    add: 'Add New MAWB', edit: 'Edit MAWB',
    part: `Part MAWB — ${activeMawb?.mawb_no}`,
    amend: `Amend MAWB — ${activeMawb?.mawb_no}`,
    'delete-confirm': `Delete MAWB — ${activeMawb?.mawb_no}`,
  };

  return (
    <div className="page-container">
      <div className="flex-between mb-16">
        <div>
          <h1 className="page-title">Master Airway Bills (MAWB)</h1>
          <p className="page-subtitle">Manage consol master airway bills for ICES 1.5 CGM transmission</p>
        </div>
        <button className="btn btn-primary" onClick={openAdd}>+ Add New MAWB</button>
      </div>

      <div className="card">
        <div className="card-header">
          <div className="search-bar" style={{ margin: 0, flex: 1 }}>
            <div className="search-input-wrap">
              <span className="search-icon">🔍</span>
              <input
                className="form-control search-input"
                placeholder="Search by MAWB No. or Origin..."
                value={search}
                onChange={e => setSearch(e.target.value)}
                onKeyDown={e => { if (e.key === 'Enter') { setPage(1); fetchMawbs(1, pageSize); } }}
                style={{ margin: 0 }}
              />
            </div>
            <button className="btn btn-secondary btn-sm" onClick={() => { setPage(1); fetchMawbs(1, pageSize); }}>Search</button>
          </div>
          <button
            className={`btn btn-sm ${showTransmitted ? 'btn-warning' : 'btn-secondary'}`}
            onClick={() => { setShowTransmitted(v => { fetchMawbs(1, pageSize, !v); return !v; }); setPage(1); }}
            style={{ whiteSpace: 'nowrap' }}
          >
            {showTransmitted ? 'Hide Transmitted' : 'Show Transmitted'}
          </button>
        </div>

        <div className="table-wrapper">
          {loading ? (
            <div className="loading-center"><span className="spinner"></span> Loading...</div>
          ) : mawbs.length === 0 ? (
            <div className="empty-state">
              <div className="empty-state-icon">📦</div>
              <div className="empty-state-title">No MAWBs found</div>
              <p>Click "Add New MAWB" to create your first master airway bill.</p>
            </div>
          ) : (
            <>
              <table>
                <thead>
                  <tr>
                    <th>MAWB No.</th>
                    <th>Type</th>
                    <th>Origin</th>
                    <th>Dest</th>
                    <th>Packages</th>
                    <th>Weight (KG)</th>
                    <th>HAWBs</th>
                    <th>Status</th>
                    <th>Transmitted</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {mawbs.map(m => (
                    <tr key={m.id}>
                      <td><span className="font-mono" style={{ fontWeight: 600 }}>{m.mawb_no}</span></td>
                      <td>{msgTypeBadge(m.message_type)}</td>
                      <td>{m.origin}</td>
                      <td>{m.destination}</td>
                      <td>{m.total_packages}</td>
                      <td>{parseFloat(String(m.gross_weight)).toFixed(2)}</td>
                      <td>
                        <span
                          className="badge badge-info"
                          style={{ cursor: 'pointer' }}
                          onClick={() => navigate(`/hawb?mawb_id=${m.id}&mawb_no=${m.mawb_no}`)}
                        >
                          {m.hawb_count || 0} HAWBs
                        </span>
                      </td>
                      <td>{statusBadge(m.status)}</td>
                      <td className="text-muted text-sm">{fmtDateTime(m.transmission_date)}</td>
                      <td>
                        <div className="td-actions">
                          <button className="btn-link" onClick={() => openEdit(m)}>Edit</button>
                          {isFreshMawb(m.mawb_no) && (
                            <>
                              <span style={{ color: 'var(--border)' }}>|</span>
                              <button className="btn-link" onClick={() => openPart(m)}>Part</button>
                              <span style={{ color: 'var(--border)' }}>|</span>
                              <button className="btn-link" onClick={() => openAmend(m)}>Amend</button>
                            </>
                          )}
                          <span style={{ color: 'var(--border)' }}>|</span>
                          <button className="btn-link danger" onClick={() => openDeleteConfirm(m)}>Delete</button>
                          {m.status !== 'transmitted' && <span style={{ color: 'var(--border)' }}>|</span>}
                          {m.status !== 'transmitted' && (
                            <button className="btn-link" onClick={() => handleDownload(m)}>Download</button>
                          )}
                          <span style={{ color: 'var(--border)' }}>|</span>
                          <button
                            className="btn-link"
                            onClick={() => handleDownloadSigned(m)}
                            disabled={signingId === m.id}
                            title="Sign CGM via Local PKI Signer and download .p7 file"
                          >
                            {signingId === m.id
                              ? <><span className="spinner" style={{ width: 10, height: 10 }}></span> Signing...</>
                              : 'Sign'}
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <Pagination
                total={total} page={page} pageSize={pageSize}
                onPage={p => { setPage(p); fetchMawbs(p, pageSize); }}
                onPageSize={ps => { setPageSize(ps); setPage(1); fetchMawbs(1, ps); }}
              />
            </>
          )}
        </div>
      </div>

      {/* MAWB Modal (Add / Edit / Part / Amend) */}
      {modalMode && modalMode !== 'delete-confirm' && (
        <div className="modal-overlay" onClick={e => { if (e.target === e.currentTarget) closeModal(); }}>
          <div className="modal modal-lg">
            <div className="modal-header">
              <span className="modal-title">{modalTitle[modalMode]}</span>
              <button className="modal-close" onClick={closeModal}>×</button>
            </div>
            <div className="modal-body">
              <p style={{ fontSize: 11, fontWeight: 700, color: 'var(--primary)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 10 }}>MAWB Details</p>

              {/* Validation warning */}
              {validationWarn && (
                <div className="alert alert-warning" style={{ marginBottom: 10, fontSize: 12 }}>
                  ⚠️ {validationWarn}
                </div>
              )}

              <div className="form-group" style={{ maxWidth: 280 }}>
                <div className="form-group">
                  <label className="form-label">Master AWB No. <span className="required">*</span></label>
                  <input
                    className="form-control font-mono"
                    value={form.mawb_no}
                    onChange={e => {
                      const max = modalMode === 'add' ? 11 : 20;
                      const clean = e.target.value.replace(/[^0-9]/g, '');
                      if (clean.length <= max) f('mawb_no', clean);
                    }}
                    placeholder="e.g. 12345678901"
                    maxLength={modalMode === 'add' ? 11 : 20}
                    disabled={mawbNoDisabled}
                    style={mawbNoDisabled ? { background: '#f1f5f9' } : {}}
                  />
                  {modalMode === 'add' && (
                    <p style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>
                      Max 11 digits ({form.mawb_no.length}/11)
                    </p>
                  )}
                  {(modalMode === 'part' || modalMode === 'amend') && (
                    <p style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>
                      New number will be: {form.mawb_no}-{modalMode === 'part' ? 'P' : 'A'}
                    </p>
                  )}
                </div>
              </div>
              <div className="form-row form-row-3">
                <div className="form-group">
                  <label className="form-label">Port Of Origin <span className="required">*</span></label>
                  {/* Always text input — user types/edits directly */}
                  <input
                    className="form-control font-mono"
                    value={form.origin}
                    onChange={e => f('origin', e.target.value.toUpperCase())}
                    placeholder="e.g. DXB"
                    maxLength={3}
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">Port Of Destination <span className="required">*</span></label>
                  {modalMode === 'add' ? (
                    <input
                      className="form-control font-mono"
                      value={form.destination}
                      disabled
                      style={{ background: '#f1f5f9', cursor: 'not-allowed' }}
                      title="Auto-filled from selected login location"
                    />
                  ) : (
                    <input
                      className="form-control font-mono"
                      value={form.destination}
                      onChange={e => f('destination', e.target.value.toUpperCase())}
                      placeholder="e.g. DEL"
                      maxLength={3}
                    />
                  )}
                </div>
                <div className="form-group">
                  <label className="form-label">Item Description</label>
                  <input className="form-control" value="CONSOL" disabled style={{ background: '#f1f5f9', fontWeight: 600 }} />
                </div>
              </div>
              <div className="form-row form-row-2">
                <div className="form-group">
                  <label className="form-label">Total Packages</label>
                  <input
                    className="form-control" type="number" value={form.total_packages}
                    onChange={e => {
                      f('total_packages', e.target.value);
                      if (modalMode === 'edit') checkHawbValidation(activeMawb?.id, e.target.value, form.gross_weight);
                    }}
                    min={0}
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">Gross Weight (KGS)</label>
                  <input
                    className="form-control" type="number" step="0.001" value={form.gross_weight}
                    onChange={e => {
                      f('gross_weight', e.target.value);
                      if (modalMode === 'edit') checkHawbValidation(activeMawb?.id, form.total_packages, e.target.value);
                    }}
                    min={0}
                  />
                </div>
              </div>

              {modalMode === 'add' && (
                <>
                  <div className="divider" />
                  <div className="flex-between" style={{ alignItems: 'flex-start', gap: 12, marginBottom: 12 }}>
                    <div>
                      <p style={{ fontSize: 11, fontWeight: 700, color: 'var(--primary)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 6 }}>
                        Add HAWBs On This Page
                      </p>
                      <p className="text-muted text-sm" style={{ margin: 0 }}>
                        Optional. You can create the MAWB and multiple HAWBs together here, or keep using the current HAWB pages.
                      </p>
                    </div>
                    <button className="btn btn-secondary btn-sm" onClick={addInlineHawbRow}>+ Add HAWB</button>
                  </div>

                  {inlineHawbs.length === 0 ? (
                    <div className="empty-state" style={{ padding: 20 }}>
                      <div className="empty-state-title">No inline HAWBs added</div>
                      <p>Use "+ Add HAWB" if you want to save HAWBs together with this MAWB.</p>
                    </div>
                  ) : (
                    <>
                      <div className="table-wrapper" style={{ marginBottom: 0 }}>
                        <table>
                          <thead>
                            <tr>
                              <th>#</th>
                              <th>HAWB No.</th>
                              <th>Origin</th>
                              <th>Destination</th>
                              <th>Packages</th>
                              <th>Weight (KGS)</th>
                              <th>Item Description</th>
                              <th></th>
                            </tr>
                          </thead>
                          <tbody>
                            {inlineHawbs.map((row, index) => (
                              <tr key={index}>
                                <td>{index + 1}</td>
                                <td>
                                  <input
                                    className="form-control font-mono"
                                    value={row.hawb_no}
                                    onChange={e => updateInlineHawbRow(index, 'hawb_no', e.target.value.replace(/[^a-zA-Z0-9]/g, ''))}
                                    placeholder="House AWB"
                                    style={{ minWidth: 120 }}
                                  />
                                </td>
                                <td>
                                  <input
                                    className="form-control font-mono"
                                    value={row.origin}
                                    onChange={e => updateInlineHawbRow(index, 'origin', e.target.value.toUpperCase())}
                                    maxLength={3}
                                    style={{ width: 90 }}
                                  />
                                </td>
                                <td>
                                  <input
                                    className="form-control font-mono"
                                    value={row.destination}
                                    onChange={e => updateInlineHawbRow(index, 'destination', e.target.value.toUpperCase())}
                                    maxLength={3}
                                    style={{ width: 90 }}
                                  />
                                </td>
                                <td>
                                  <input
                                    className="form-control"
                                    type="number"
                                    value={row.total_packages}
                                    onChange={e => updateInlineHawbRow(index, 'total_packages', e.target.value)}
                                    min={0}
                                    style={{ width: 100 }}
                                  />
                                </td>
                                <td>
                                  <input
                                    className="form-control"
                                    type="number"
                                    step="0.001"
                                    value={row.gross_weight}
                                    onChange={e => updateInlineHawbRow(index, 'gross_weight', e.target.value)}
                                    min={0}
                                    style={{ width: 110 }}
                                  />
                                </td>
                                <td>
                                  <input
                                    className="form-control"
                                    value={row.item_description}
                                    onChange={e => updateInlineHawbRow(index, 'item_description', e.target.value.replace(/[^a-zA-Z0-9 .,\-/]/g, ''))}
                                    placeholder="AS PER INVOICE"
                                    maxLength={30}
                                    style={{ minWidth: 160 }}
                                  />
                                </td>
                                <td>
                                  <button className="btn-link danger" onClick={() => removeInlineHawbRow(index)}>Delete</button>
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>

                      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, marginTop: 10, flexWrap: 'wrap', fontSize: 12 }}>
                        <span className="text-muted">Rows ready: {inlineHawbCount}</span>
                        <input
                          type="number"
                          placeholder="Generate HAWBs (e.g. 90)"
                          className="form-control"
                          style={{ width: 180 }}
                          onBlur={(e) => generateHawbRows(parseInt(e.target.value || '0', 10))}
                        />
                        <span className="text-muted">HAWB totals: {inlineHawbTotalPackages} packages / {inlineHawbTotalWeight.toFixed(3)} KGS</span>
                      </div>

                      {showInlineTotalsWarning && (
                        <div className="alert alert-warning" style={{ marginTop: 10, fontSize: 12 }}>
                          HAWB totals do not match the MAWB totals yet. You can still save draft data and adjust it later.
                        </div>
                      )}
                    </>
                  )}
                </>
              )}

              {/* Flight details – shown in edit/part/amend */}
              {showFlightDetails && (
                <>
                  <div className="divider" />
                  <p style={{ fontSize: 11, fontWeight: 700, color: 'var(--primary)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 10 }}>Flight Details</p>
                  <div className="form-row form-row-2">
                    <div className="form-group">
                      <label className="form-label">Flight No.</label>
                      <input className="form-control" value={form.flight_no} onChange={e => f('flight_no', e.target.value)} placeholder="e.g. AI123" maxLength={15} />
                    </div>
                    <div className="form-group">
                      <label className="form-label">Flight Date</label>
                      <input className="form-control" type="date" value={form.flight_origin_date} onChange={e => f('flight_origin_date', e.target.value)} />
                    </div>
                  </div>
                  <div className="form-row form-row-2">
                    <div className="form-group">
                      <label className="form-label">IGM No.</label>
                      <input className="form-control" value={form.igm_no} onChange={e => f('igm_no', e.target.value)} placeholder="Enter IGM No" maxLength={7} />
                    </div>
                    <div className="form-group">
                      <label className="form-label">IGM Date</label>
                      <input className="form-control" type="date" value={form.igm_date} onChange={e => f('igm_date', e.target.value)} />
                    </div>
                  </div>
                </>
              )}
            </div>
            <div className="modal-footer">
              <button className="btn btn-primary" onClick={handleSave} disabled={saving}>
                {saving ? <><span className="spinner" style={{ width: 12, height: 12 }}></span> Saving...</> : 'Save'}
              </button>
              <button className="btn btn-secondary" onClick={closeModal}>Cancel</button>
            </div>
          </div>
        </div>
      )}

      {/* Delete Confirm Dialog — shows MAWB + flight details + delete options */}
      {modalMode === 'delete-confirm' && activeMawb && (
        <div className="modal-overlay">
          <div className="modal" style={{ maxWidth: 560 }}>
            <div className="modal-header">
              <span className="modal-title">Delete MAWB — {activeMawb.mawb_no}</span>
              <button className="modal-close" onClick={() => setModalMode(null)}>×</button>
            </div>
            <div className="modal-body">
              {/* MAWB summary */}
              <div style={{ background: '#f8fafc', borderRadius: 6, padding: '10px 14px', marginBottom: 14, fontSize: 12 }}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '4px 16px' }}>
                  <div><span className="text-muted">MAWB No:</span> <strong className="font-mono">{activeMawb.mawb_no}</strong></div>
                  <div><span className="text-muted">Route:</span> <strong>{activeMawb.origin} → {activeMawb.destination}</strong></div>
                  <div><span className="text-muted">Packages:</span> <strong>{activeMawb.total_packages}</strong></div>
                  <div><span className="text-muted">Weight:</span> <strong>{parseFloat(String(activeMawb.gross_weight)).toFixed(2)} KGS</strong></div>
                </div>
              </div>

              {/* Flight details for Delete & Copy */}
              <div style={{ border: '1px solid var(--border)', borderRadius: 8, padding: 14, marginBottom: 14 }}>
                <p style={{ fontSize: 12, fontWeight: 700, color: 'var(--primary)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 10 }}>
                  Flight Details (for Delete Copy)
                </p>
                <div className="form-row form-row-2" style={{ marginBottom: 8 }}>
                  <div className="form-group" style={{ marginBottom: 0 }}>
                    <label className="form-label">Flight No.</label>
                    <input className="form-control" value={form.flight_no} onChange={e => f('flight_no', e.target.value)} placeholder="e.g. AI123" maxLength={15} />
                  </div>
                  <div className="form-group" style={{ marginBottom: 0 }}>
                    <label className="form-label">Flight Date</label>
                    <input className="form-control" type="date" value={form.flight_origin_date} onChange={e => f('flight_origin_date', e.target.value)} />
                  </div>
                </div>
                <div className="form-row form-row-2">
                  <div className="form-group" style={{ marginBottom: 0 }}>
                    <label className="form-label">IGM No.</label>
                    <input className="form-control" value={form.igm_no} onChange={e => f('igm_no', e.target.value)} placeholder="Enter IGM No" maxLength={7} />
                  </div>
                  <div className="form-group" style={{ marginBottom: 0 }}>
                    <label className="form-label">IGM Date</label>
                    <input className="form-control" type="date" value={form.igm_date} onChange={e => f('igm_date', e.target.value)} />
                  </div>
                </div>
              </div>

              <p style={{ marginBottom: 12, fontWeight: 500 }}>Choose how to delete this MAWB:</p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                <div style={{ border: '1px solid var(--border)', borderRadius: 8, padding: 14 }}>
                  <div style={{ fontWeight: 600, marginBottom: 4 }}>1. Permanent Delete</div>
                  <p className="text-muted text-sm" style={{ marginBottom: 12 }}>
                    Completely removes this MAWB and all its HAWBs. Cannot be undone.
                  </p>
                  <button className="btn btn-sm" style={{ background: '#ef4444', color: '#fff' }} onClick={handlePermanentDelete} disabled={saving}>
                    Permanently Delete
                  </button>
                </div>
                <div style={{ border: '1px solid var(--border)', borderRadius: 8, padding: 14 }}>
                  <div style={{ fontWeight: 600, marginBottom: 4 }}>2. Delete &amp; Copy (message type D)</div>
                  <p className="text-muted text-sm" style={{ marginBottom: 12 }}>
                    Creates a new MAWB with suffix <strong>-D1</strong> and message type D for customs submission.
                    New number: <strong>{activeMawb.mawb_no.replace(/-[APD]\d+$/, '')}-D?</strong>
                  </p>
                  <button className="btn btn-sm btn-secondary" onClick={handleDeleteCopy} disabled={saving}>
                    Delete &amp; Copy
                  </button>
                </div>
              </div>
            </div>
            <div className="modal-footer">
              <button className="btn btn-secondary" onClick={() => setModalMode(null)}>Cancel</button>
            </div>
          </div>
        </div>
      )}


    </div>
  );
};

export default MawbPage;
