import React from 'react';

// ICES 1.5 Sea (Consol/CGM) error codes.
const SEA_ERRORS = [
  { code: '000', desc: 'Consol IGM Submitted' },
  { code: '200', desc: 'Cargo Details Validated' },
  { code: '201', desc: 'Incorrect Message Type' },
  { code: '202', desc: 'Consigm Number/Date cannot be NULL' },
  { code: '203', desc: 'Incorrect Consigm No. /Date - Does not Exist' },
  { code: '204', desc: 'Line Number cannot be NULL' },
  { code: '205', desc: 'Line No cannot be Zero / Negative / Fraction' },
  { code: '206', desc: 'Incorrect Line No. - Does not Exist' },
  { code: '207', desc: 'SubLine Number cannot be NULL' },
  { code: '208', desc: 'Only ZERO allowed in SubLine. Cannot be NULL / Negative / Fraction' },
  { code: '209', desc: 'Incorrect Subline No. - Does not Exist' },
  { code: '210', desc: 'Vessel Code cannot be Amended' },
  { code: '211', desc: 'Voyage No cannot be Amended' },
  { code: '212', desc: 'Port of Destination is Incorrect' },
  { code: '213', desc: 'Port of Shipment in Incorrect' },
  { code: '214', desc: 'Port of Shipment is same as Port of Destination' },
  { code: '215', desc: 'Nature of Cargo is incorrect' },
  { code: '216', desc: 'This Amendment NOT ALLOWED! - DELETE this Line and ADD correct Line as Supplement' },
  { code: '217', desc: 'This Amendment NOT ALLOWED! - DELETE the Container Details and then do the Amendment' },
  { code: '218', desc: 'Gross weight/Unit cannot be NULL or Zero/Negative when nature cargo is DB/C/P/CP' },
  { code: '219', desc: 'Gross Volume / Unit should be null when nature cargo is DB/C/P/CP' },
  { code: '220', desc: 'Gross Volume/Unit cannot be Null/Zero/Negative when nature cargo is LB' },
  { code: '221', desc: 'Gross Weight / Unit should be null when nature cargo is LB' },
  { code: '222', desc: 'Cargo Movement is Wrong' },
  { code: '223', desc: 'Port Dest is Invalid for Cargo Mvnt=LC' },
  { code: '224', desc: 'Port Dest is Invalid for Cargo Mvnt=TC/TI' },
  { code: '225', desc: 'Port Dest is Invalid for Cargo Mvnt=TI' },
  { code: '226', desc: 'Port Dest is Invalid for Cargo Mvnt=TC' },
  { code: '227', desc: 'Unit of Quantity is incorrect' },
  { code: '228', desc: 'Unit of Volume is incorrect' },
  { code: '229', desc: 'Total Package cannot be NULL/ Zero / Negative / Fraction' },
  { code: '230', desc: 'Package Code is incorrect' },
  { code: '231', desc: 'Both UNO and IMCO Code should be NULL or should not be NULL' },
  { code: '232', desc: 'Invalid UNO code' },
  { code: '233', desc: 'Item Type is incorrect' },
  { code: '234', desc: 'Cargo Details not found' },
  { code: '235', desc: 'HBL No. can not be NULL' },
  { code: '236', desc: 'Port of Destination cannot be NULL' },
  { code: '237', desc: 'Port of Shipment cannot be NULL' },
  { code: '238', desc: 'BL Number cannot be NULL' },
  { code: '239', desc: 'BL No has Special Characters' },
  { code: '240', desc: 'BL Date cannot be NULL' },
  { code: '241', desc: 'BL Date cannot be greater than arrival date' },
  { code: '242', desc: "BL Date cannot be greater than today's date" },
  { code: '243', desc: 'BL Date cannot be older than ONE YEAR' },
  { code: '244', desc: 'House BL No. should be NULL' },
  { code: '246', desc: 'Nature Cargo can not be NULL' },
  { code: '247', desc: 'Cargo Movement can not be NULL' },
  { code: '248', desc: 'Package Code can not be NULL' },
  { code: '249', desc: 'Marks and Numbers cannot be NULL' },
  { code: '250', desc: 'Goods Description cannot be NULL' },
  { code: '251', desc: 'Importer Name cannot be NULL' },
  { code: '252', desc: 'Importer Address cannot be NULL' },
  { code: '253', desc: 'UNO Code cannot be NULL' },
  { code: '254', desc: 'IMCO Code cannot be NULL' },
  { code: '255', desc: 'Item Type can not be NULL' },
  { code: '256', desc: 'Mode Transport cannot be NULL for Transhipment cargo in line no.' },
  { code: '257', desc: 'Carrier Code is Incorrect' },
  { code: '258', desc: 'Incorrect Bond No' },
  { code: '259', desc: 'Wrong Mode of Transport' },
  { code: '260', desc: 'Incorrect MLO Code' },
  { code: '261', desc: 'Duplicate Cargo SubLine' },
  { code: '262', desc: 'Duplicate HBL NO. exists in SubLine Number' },
  { code: '263', desc: 'Duplicate SubLine NO. exists for HBL No' },
  { code: '264', desc: 'All Containers Rejected' },
  { code: '265', desc: 'CARN No. is not Valid' },
  { code: '266', desc: 'Consigm Number/Date cannot be given in Fresh IGM' },
  { code: '267', desc: 'Vessel code And voyage no is Not matching in vessel and Cargo details' },
  { code: '268', desc: 'HBL Date can not be NULL' },
  { code: '269', desc: 'HBL Number cannot be NULL if HBL date is given' },
  { code: '270', desc: 'HBL No has Special Characters' },
  { code: '271', desc: 'HBL Date cannot be NULL if HBL No. is given' },
  { code: '272', desc: 'SubLine NO. already exists with same HBL No' },
  { code: '274', desc: 'HBL Date cannot be greater than arrival date' },
  { code: '275', desc: "HBL Date cannot be greater than today's date" },
  { code: '276', desc: 'HBL Date cannot be older than ONE YEAR' },
  { code: '277', desc: 'No Container for Containerised Cargo' },
  { code: '278', desc: 'Container given for Non-Containerised Cargo' },
  { code: '279', desc: 'Unit of quantity cannot be NULL' },
  { code: '280', desc: 'Invalid IMCO Code' },
  { code: '281', desc: 'Destination Code cannot be NULL' },
  { code: '282', desc: 'Destination Code is invalid' },
  { code: '283', desc: 'Destination Code cannot be Amended' },
  { code: '284', desc: 'House BL Date. should be NULL' },
  { code: '285', desc: 'BL Number cannot be Amended' },
  { code: '286', desc: 'BL Date cannot be Amended' },
  { code: '287', desc: 'MLO Code Cannot be NULL' },
  { code: '291', desc: 'Cargo Supplement Rejected' },
  { code: '297', desc: 'Cargo Deletion Submitted' },
  { code: '298', desc: 'Cargo Supplement Submitted' },
  { code: '299', desc: 'Cargo Amendment Submitted' },
  { code: '300', desc: 'Container Details Validated' },
  { code: '301', desc: 'Incorrect Message Type' },
  { code: '302', desc: 'Consigm Number/Date cannot be NULL' },
  { code: '303', desc: 'Incorrect Consigm No. /Date - Does not Exist' },
  { code: '304', desc: 'Line No cannot be NULL / Zero / Negative / Fraction' },
  { code: '305', desc: 'Incorrect Line No. - Does not Exist' },
  { code: '306', desc: 'Only ZERO allowed in SubLine. Cannot be NULL / Negative / Fraction' },
  { code: '307', desc: 'Incorrect Subline No. - Does not Exist' },
  { code: '308', desc: 'Container Number cannot be NULL' },
  { code: '309', desc: 'Incorrect Container No. - Does not Exist' },
  { code: '310', desc: 'Container line exists without Cargo' },
  { code: '311', desc: 'Container line exists for Non-Containerised cargo' },
  { code: '312', desc: 'Container Status can be FCL or LCL or EMP only' },
  { code: '313', desc: 'Vessel Code cannot be Amended' },
  { code: '314', desc: 'Voyage No. cannot be Amended' },
  { code: '315', desc: 'Total Package cannot be NULL / Zero / Negative / Fraction' },
  { code: '316', desc: 'Container Weight Cannot be Zero/Negative/ NULL' },
  { code: '317', desc: 'Container Weight Cannot be greater than 99.99 tons' },
  { code: '318', desc: 'Invalid ISO Code' },
  { code: '319', desc: 'SOC can be only [Y]es or [N]o' },
  { code: '320', desc: 'Container Details Not Found' },
  { code: '321', desc: 'Container already Exists cannot add' },
  { code: '322', desc: 'Container status cannot be NULL' },
  { code: '323', desc: 'Total Packages should be Zero for Cont Status=EMP' },
  { code: '324', desc: 'ISO Code cannot be NULL' },
  { code: '325', desc: 'Seal No. Cannot be NULL' },
  { code: '327', desc: 'Container Exists with FCL / EMP Status in different Cargo Line' },
  { code: '328', desc: 'Line Rejected' },
  { code: '329', desc: 'Consigm Number/Date cannot be given in Fresh IGM' },
  { code: '330', desc: 'CARN No. not valid' },
  { code: '331', desc: 'CARN No. not matching with cargo master' },
  { code: '332', desc: 'Deletion NOT Possible - Only Container' },
  { code: '341', desc: 'SEAL No. not matching for LCL container' },
  { code: '342', desc: 'ISO Code not matching for LCL container' },
  { code: '391', desc: 'Container Supplement Rejected' },
  { code: '397', desc: 'Container Deletion Submitted' },
  { code: '398', desc: 'Container Supplement Submitted' },
  { code: '399', desc: 'Container Amendment Submitted' },
  { code: '400', desc: 'Late Submission of CONSOL - Pending for Approval' },
  { code: '401', desc: 'Cargo Amendment Submitted and Auto-Approved' },
  { code: '402', desc: 'Cargo Deletion Submitted and Auto-Approved' },
  { code: '403', desc: 'Cargo Supplement Submitted and Auto-Approved' },
  { code: '404', desc: 'Conatiner Amendment Submitted and Auto-Approved' },
  { code: '405', desc: 'Contanier Deletion Submitted and Auto-Approved' },
  { code: '406', desc: 'Container Supplement Submitted and Auto-Approved' },
  { code: '451', desc: 'IMO Code / Vessel Code/ Voyage No. have to be given' },
  { code: '452', desc: 'IMO Code / Vessel Code have to be valid values' },
  { code: '453', desc: 'BL No./ BL Date Not matching with corresponding IGM' },
  { code: '461', desc: 'IMO Code / Vessel Code/ Voyage No. have to be given' },
  { code: '462', desc: 'IMO Code / Vessel Code have to be valid values' },
  { code: '463', desc: 'Container No. Not matching with corresponding IGM' },
  { code: '464', desc: 'IMO Code / Vessel Code/ Voyage No. Not matching with Cargo Master' },
  { code: '501', desc: 'Only Alpha-Numeic Characters Allowed in Voyage No.' },
  { code: '502', desc: 'Only Alpha-Numeic Characters Allowed in Cont. Agent Code' },
  { code: '503', desc: 'Transshippment for Line done' },
  { code: '504', desc: 'Transshippment for Container done' },
  { code: '506', desc: 'B.O.E. is already filed' },
  { code: '601', desc: 'Data Length Error or Value Large Error' },
];

const SeaErrorCodePage: React.FC = () => {
  return (
    <div className="page-container" style={{ paddingTop: '72px', paddingBottom: '24px', maxWidth: '1400px', margin: '0 auto', border: '1px solid #ccc', borderRadius: '8px', padding: '20px', backgroundColor: '#f9f9f9' }}>
      <div className="errorcode-page">
        <h1>ICES 1.5 Sea (Consol/CGM) Error Codes</h1>
        <table>
          <thead>
            <tr>
              <th>Code</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            {SEA_ERRORS.map((error) => (
              <tr key={error.code}>
                <td>{error.code}</td>
                <td>{error.desc}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default SeaErrorCodePage;
